### ISSUE TITLE
Option to hide currency symbol

### ISSUE THREAD

**Issue by PanderMusubi** [hwki/SimpleBitcoinWidget#10]
Please, add an option to hide or show the currency symbol. This can decrease the amount of questions one get about what this widget represents or avoid attracting unwanted attention.

**Comment by hwki** [comment]
I'm not sure what you're getting at with this request. I see no need to prevent questions or avoid "attracting unwanted attention". This request implies there's something shady in showing the current price of bitcoin?

**Comment by PanderMusubi** [comment]
If you have **€ 1600** in a widget on your screen, that might give over-the-shoulder browsers some insight into your financial situation.

**Comment by hwki** [comment]
The widget only shows the current exchange rate, and has nothing to do with any personal financial info.

**Comment by PanderMusubi** [comment]
I know that it is only the rate. The feature request is simply to offer not showing the currency sign (for whatever personal reason, e.g. avoiding questions from others).
