### ISSUE TITLE
Add TANGO (TangoSwap) Token

### ISSUE THREAD

**Issue by ianblas** [hwki/SimpleBitcoinWidget#100]
Hi, please add the tangoswap.cash token

Price:  https://coinmarketcap.com/currencies/tangoswap/

You can also take from https://hoo.com/innovation/tango-usdt

Token Logo: https://drive.google.com/file/d/16DlJJj4VMxj2LNDTKLorVr5CGfpHiDm5/view?usp=drivesdk

**Comment by hwki** [comment]
added with partial support with coingecko
