### ISSUE TITLE
No automatic refresh

### ISSUE THREAD

**Issue by haarp** [hwki/SimpleBitcoinWidget#101]
Hi,

for the longest time, I notic problems with these widgets not refreshing automatically. Currently on version 8.2 on LineageOS 17.1 and refresh interval set to 30 minutes. Manual refresh by tapping on them works fine. I believe they do work for a while after a restart, but cannot confirm this for sure. Not sure what to do about this.

Thanks!

**Comment by hwki** [comment]
Unfortunately a number of devices cause issues with apps running in the background, as well as android restricting it more and more with each release. I haven't tested against LineageOS though, so I can't say for certain.

Can you check that battery optimization is turned off for the app? Looks like it should be under: Settings -> Apps -> Simple Crypto Widget -> Battery -> Battery Optimization -> Pull Down Menu to Choose All Apps -> Turn Optimization Off Per App

You can also try opening the app again, and go to setting and choose a different refresh interval. This should at least reenable the work manager if it somehow got disabled.

**Comment by haarp** [comment]
Thanks. I've already had disabled Battery Optimization to no avail. Changing the interval did indeed restart the updater service, but I guess it's only a matter of time until it disappears ago.

It's weird, because LineageOS isn't deploying aggressive app killers like some brands do. It's fairly close to vanilla Android (Android 10 in my case)

**Comment by hwki** [comment]
I agree its odd that its happening with LineageOS. This isn't the first report I've gotten about this, but usually its due to device manufacturers killing background apps. There must be some set of circumstances that causes the work to get cancelled but I'm not sure what that would be. Can I ask how many widgets you have created?

**Comment by haarp** [comment]
> Can I ask how many widgets you have created?

just two

**Comment by hwki** [comment]
If you see it happen again, I'm curious what standby bucket android put the app in. You can check this in Settings > System > Developer Options > Standby apps. Might tell us if android thinks the app is running too much in the background and restricting it.

**Comment by haarp** [comment]
Standby state is EXEMPTED (due to Battery Optimizations being disabled?)

Right now the widgets seems to still be updating without problems. Will check again when it stops.

Thanks!
