### ISSUE TITLE
All ARS exchange rate are wrong

### ISSUE THREAD

**Issue by ianblas** [hwki/SimpleBitcoinWidget#102]
Hello the ARS exchange rate that the app has is wrong, it does not accurately reflect the true market price of the crypto, making it appear as overvalued when in fact it is because the price is calculated using the official exchange rate (chosen by the government).

We use the yadio API (https://www.yadio.io/today.html) for the real exchange rate and several services (Bitcoin.com wallet, Electron Cash, Localcryptos.com and others) use it to show the ARS value of Bitcoin Cash and other crypto.

**Comment by hwki** [comment]
The app only shows the prices as reported by each exchange's API, so I would say it accurately reflects the value each exchange says.
What I can do instead is add the Yadio API as an available exchange in the app so you can rates from there. (Although Yadio looks to be only Bitcoin?)

**Comment by ianblas** [comment]
The CRYPTO-ARS exchange rate shown by the non-Argentine exchange is wrong, they take the government exchange rate (1 USD = 115 ARS) instead of the market exchange rate (1 USD = 220 USD). The yadio API shows the correct USD/ARS exchange rate, it just multiplies the USD price of the crypto by the Yadio USD/ARS.

**Comment by hwki** [comment]
Yes I get that, but the widget shows the reported prices by the exchanges. I can't go down the road of trying to interpret whether the rates listed by the exchanges are accurate or using another service to convert them. I will add Yadio in the next update so at least prices from there can be used.
