### ISSUE TITLE
Suddenly no Exchange data available 

### ISSUE THREAD

**Issue by theAkito** [hwki/SimpleBitcoinWidget#103]
I'm using this app since a very long time. Thank you for creating and publishing it on F-Droid.

Suddenly, apparently since the last update, I cannot see any rates anymore, because there are "no exchanges found" for any coin.

![b4d0ac27-943a-4aa7-83f8-7f967b8b9d19.png](https://user-images.githubusercontent.com/26848976/155662264-3e44af07-70bf-4723-8ca9-5140ce3bdf04.png)

It does not matter which coin is selected. It seems like there is a connection block or whatever. However, this never happened before and I did not change any settings regarding this app.

I also cannot re-install the app, as there is no Backup option available, which means I would need to re-set up everything from scratch on re-installation.

**Comment by hwki** [comment]
@theAkito I believe this happens when there is a corrupted download of the coin/exchange data. I have uploaded a new version, please give it another try and let me know if it works for you. I need to fix this in the app to handle it better.
