### ISSUE TITLE
Widget bigger than before

### ISSUE THREAD

**Issue by quamok** [hwki/SimpleBitcoinWidget#104]
Hello there, since upgrading to Android 12, I can't seem to adjust down the widget size. I'm not sure if this is the new intended behavior or not. You can see in the picture the older widgets (smaller ones) and the newer widgets (bigger ones). I can't make the bigger ones smaller. It seems to me that this is wasting too much unused home screen space.

Thanks!

![Screenshot_20220329-091436](https://user-images.githubusercontent.com/24906799/160622127-b3a40f9d-7fb3-4e07-9b89-eb7ef254e16a.png)

**Comment by hwki** [comment]
No, the min cell height is 1, min width is 2, so you should be able to resize those widgets height to be the same as the others. What exactly happens if you long press on them and try to resize? Also what launcher are you using?

**Comment by quamok** [comment]
Running Android 12, CalyxOS v3.3.0, Quickstep v12

https://user-images.githubusercontent.com/24906799/160642510-cbff51db-1f66-4e0f-8fbf-333159bd1f44.mp4

**Comment by hwki** [comment]
This seems to be a bug with the Quickstep launcher for CalyxOS. Especially the fact that the existing widgets there have no problem being that size. I would recommend confirming by testing out on a different launcher and adding a bug on their bug tracker: https://gitlab.com/CalyxOS/calyxos/-/issues. 

Android 12 is supposed to follow the minCellHeight and minCellWidth attributes defined by the app. It definitely works for other launchers.

**Comment by quamok** [comment]
Thanks a lot for looking into this, I've taken your suggestion and went over the CalyxOS Gitlab page.

Have a good day!
