### ISSUE TITLE
Add limit alarms

### ISSUE THREAD

**Issue by Forage** [hwki/SimpleBitcoinWidget#106]
A great nice and simple app, thank you for your efforts and making this available.

One feature I'd love to see added is setting an alarm/notification for when a certain threshold is reached. For example when the current price or wallet value surpasses a set upper threshold and the same for when it drops below a certain value.

What do you think?

**Comment by hwki** [comment]
While I agree that it would be a nice feature, and it has been requested before.. with the amount of effort involved to add and support this feature I don't think I will be including it.
