### ISSUE TITLE
Widget insists on taking up 2 rows

### ISSUE THREAD

**Issue by luke-jr** [hwki/SimpleBitcoinWidget#107]
For some reason, the widget won't let me size it to a single row, even though it would very easily fit.

**Comment by hwki** [comment]
The minimum size for the widget is 1 cell high and 2 cells wide. If this is not the case for you please let me know what version of android and what launcher you are using.

**Comment by luke-jr** [comment]
Using a custom build of LineageOS's Trebuchet allowing for a 6x8 grid. In theory, that should mean each square is at most 180x266, far in excess of 40x40.

**Comment by hwki** [comment]
Ok. its actually 40 density independent pixels.. but even that should mean your grid size is minimum 45. But there's probably not a need for the minimum size at all, so I'll try removing them in the next update.

**Comment by luke-jr** [comment]
I imagine there's probably some margin, so if those numbers work out to 45, it may be cutting it too close.

Dropping the minimum sounds like a good idea (or maybe 1x1 so it can't be 0x0)
