### ISSUE TITLE
Please add Satoshis

### ISSUE THREAD

**Issue by frozear** [hwki/SimpleBitcoinWidget#108]
Can we have a currency option that displays Satoshis? As you probably know, a Satoshi is simply 1/100000000 of a Bitcoin.

**Comment by hwki** [comment]
This is already an option. For example, if you create a new Bitcoin widget, under "Denomination" you can select to show as "Sat". This will give you how much 1 SAT is worth in USD or whatever fiat currency you select.

Or if you are looking for another token as satoshi, you can create that new widget and select BTC as the currency, then choose "Sat" for the denomination.

**Comment by frozear** [comment]
Thank you. It doesn't seem like there's a universally agreed upon symbol for a Satoshi anyways.
