### ISSUE TITLE
It never refreshes with Data Saver on even when connected to Wi-Fi

### ISSUE THREAD

**Issue by J053Fabi0** [hwki/SimpleBitcoinWidget#109]
Hello.

As the title says. I think that's an error.

**Comment by hwki** [comment]
This works for me. Can you give me more details like what device and launcher you are using?

**Comment by J053Fabi0** [comment]
It's a Galaxy S21 Ultra SM-G9980 using the [Kiss Launcher](https://f-droid.org/en/packages/fr.neamar.kiss/) version 3.16.

**Comment by hwki** [comment]
Should be fixed with 8.2.6.
