### ISSUE TITLE
coinbase showing wrong price

### ISSUE THREAD

**Issue by raedah** [hwki/SimpleBitcoinWidget#11]
Seems stuck at $1638. Other sources are clearly showing me $1679 and growing.

**Comment by hwki** [comment]
It shows $1679 for me right now. What refresh rate do you have for the widget? It's possible that if you make too many requests in a short period of time, Coinbase could temporary limit you.

**Comment by raedah** [comment]
I dont recall making a lot of request, and the price wasnt updating even with the tap to refresh. Will reopen if it returns. Could have been an issue on coinbases side for a particular end point perhaps.

**Comment by maestro-brentpanther** [comment]
The only other possibility I can think of is if your phone was in Data Saver mode. The widget wouldn't be allowed to access the internet due to battery restrictions and it wouldn't update.
