### ISSUE TITLE
BCH and BSV share same bitcoin-cash designation

### ISSUE THREAD

**Issue by jaedog** [hwki/SimpleBitcoinWidget#112]
Looks like the update to the new UI is preventing BCH from being a selectable asset: [a788ba9859834e41fd383887ac7c54eda14e466a](https://github.com/hwki/SimpleBitcoinWidget/commit/a788ba9859834e41fd383887ac7c54eda14e466a)

**Comment by hwki** [comment]
Fixed with fbcb57a
