### ISSUE TITLE
[Feature Suggestion] Read from wallet balance

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [hwki/SimpleBitcoinWidget#113]
The "Amount Held" feature is useful but for us who send and receive cryptocurrency regularly we need to manually update the value after each transaction for the amount to be accurate. I suggest adding support for wallet balance reading so the value is always up to date. Bitcoin wallet balances are publicly shown but Monero wallets require a View Key to see their balances. I think it could be a good feature.

**Comment by hwki** [comment]
This is not easily done. My understanding is for bitcoin it would require reading the blockchain ledger and that would add significant complexity to the app. Each coin would be different as well so support would be limited.

I also cannot find any good public APIs to get this infomation.

So while I agree it would be useful to the end user this won't be implemented.
