### ISSUE TITLE
Xiaomi crash

### ISSUE THREAD

**Issue by xmha97** [hwki/SimpleBitcoinWidget#114]
Crash occurs on Xiaomi devices!

https://user-images.githubusercontent.com/23485114/208191114-f168849c-d4b1-43e5-862f-f935928c1d22.mp4

**Comment by hwki** [comment]
Thanks for the video. I've seen that this isn't the only app having issues with xiamoi lately. Unfortunately without a device to reproduce the issue on I can't even begin to troubleshoot.

**Comment by hwki** [comment]
@xmha97 Would you be willing to test out some builds for me to try and figure this out?

**Comment by xmha97** [comment]
> @xmha97 Would you be willing to test out some builds for me to try and figure this out?

Yes, of course.

**Comment by hwki** [comment]
Great! This one is a shot in the dark, but can you give this build a try please? @xmha97 
[https://www.brentpanther.com/bitcoin-test.apk](https://www.brentpanther.com/bitcoin-test.apk)

**Comment by xmha97** [comment]
> Great! This one is a shot in the dark, but can you give this build a try please? @xmha97 
> [https://www.brentpanther.com/bitcoin-test.apk](https://www.brentpanther.com/bitcoin-test.apk)

Thanks, this build is working fine. 👍

![Screenshot_2022-12-17-03-12-42-192_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/208208949-0e14e769-b459-4cc6-9ad0-84f03336c976.jpg)

**Comment by hwki** [comment]
Great! Thanks for your help @xmha97.
Fixed in 8.3.7
