### ISSUE TITLE
Themed Icon Support for Android 13

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [hwki/SimpleBitcoinWidget#122]
Please consider adding themed icon support. The current icon makes the app stand out as being old on modern versions of Android. Thanks :)

https://proandroiddev.com/android-13-implementing-themed-icons-into-your-app-e7002f2c4e04

**Comment by hwki** [comment]
Themed icon support already exists as of version 8.3

![Screenshot_20230428_094627](https://user-images.githubusercontent.com/571913/235179434-adb59367-567e-4338-adc4-25e7ce9d9641.png)
