### ISSUE TITLE
permission_ replace bitcoin add on fdroid

### ISSUE THREAD

**Issue by ghost** [hwki/SimpleBitcoinWidget#125]
@hwki 
* is it **ok to replace** bitcoin address given in https://github.com/hwki/SimpleBitcoinWidget#donations
* bitcoin link in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/HEAD/metadata/com.brentpanther.bitcoinwidget.yml) will replace it on fdroid client

**Comment by hwki** [comment]
@jindam-vani If i understand, you'd like to replace the bitcoin address listed in F-Droid to match the one listed in Github? If so, yes, that would be great. Thanks.
