### ISSUE TITLE
Allow manual update in battery saving mode

### ISSUE THREAD

**Issue by stevenroose** [hwki/SimpleBitcoinWidget#126]
I like that the widget doesn't auto refresh when in battery saving mode.

But when I manually hit the widget, I would like it to update. This way, in battery saving, it only updates when I want it to..

Thanks!

**Comment by hwki** [comment]
The widget doesn't refresh when in battery saving mode because it can't. Android restricts apps from using data in the background (which applies to all widgets) when battery saver is on, so unfortunately that applies when trying to manually update as well.
