### ISSUE TITLE
Add Binance Exchange

### ISSUE THREAD

**Issue by ohari5336** [hwki/SimpleBitcoinWidget#130]
please add exchange Binance if is it possible.

**Comment by hwki** [comment]
Both Binance.com and Binance.us are currently supported exchanges for all the fully integrated coins. 

For the rest, like LRS (that show up after searching as "More from CoinGecko") they will only work with CoinGecko.

LRS in particular isn't tradable on Binance or any other exchange that is currently integrated in the app.
