### ISSUE TITLE
Unable to create new widget

### ISSUE THREAD

**Issue by DReffects** [hwki/SimpleBitcoinWidget#131]
Unfortunately nothing happens, when hitting the + button to add a widget. 

Both on Android 13 and 14 Devices Mi 11 Ultra and Mi 14 Ultra.

How can I troubleshoot this? :)

**Comment by hwki** [comment]
What launcher are you using, and do you use a live wallpaper?

Does it work if you try to create the widget from the home screen instead of through the app?

**Comment by DReffects** [comment]
Thanks for the feedback! Was actually a phone issue where everything broke after importing data from an old phone. After a full phone reset it works like a charm 😃
