### ISSUE TITLE
Support Dash

### ISSUE THREAD

**Issue by PanderMusubi** [hwki/SimpleBitcoinWidget#19]
Could you please support Dash, see also https://en.wikipedia.org/wiki/Dash_%28cryptocurrency%29

**Comment by hwki** [comment]
Added

**Comment by PanderMusubi** [comment]
Thanks. Can you add a release at https://github.com/hwki/SimpleBitcoinWidget/releases so that it can get build for F-Droid?

**Comment by hwki** [comment]
It's there. btc-6.0.1

**Comment by PanderMusubi** [comment]
thanks

**Comment by PanderMusubi** [comment]
See this merge request af F-Droid. Thumbs up is welcome. https://gitlab.com/fdroid/fdroiddata/merge_requests/2770
