### ISSUE TITLE
Add F-Droid entry for Bitcoin Cash Widget

### ISSUE THREAD

**Issue by hwki** [hwki/SimpleBitcoinWidget#20]

**Comment by PanderMusubi** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/2475

**Comment by PanderMusubi** [comment]
Please extend badges in README once this merge request has been completed. Website F-Droid might lag to F-Droid client, so don't wait for that.

**Comment by PanderMusubi** [comment]
Merge has been accepted.
