### ISSUE TITLE
Offer option to show coin name

### ISSUE THREAD

**Issue by PanderMusubi** [hwki/SimpleBitcoinWidget#21]
Please offer option to show coin name next to where exchange label is shown. For example `coinbase` or `btc` or `coinbase btc` if exchange label is shown, coin name is shown of both are shown, respectively.

**Comment by gabsoftware** [comment]
Yes that would be the nicest addition, I really have a hard time remembering the coins icons!

**Comment by hwki** [comment]
Added with 8.0
