### ISSUE TITLE
Bitcoin Cash widget value flips between current value & +-$676 on every second tap

### ISSUE THREAD

**Issue by riaanjutte** [hwki/SimpleBitcoinWidget#28]
Every time I tap the Bitcoin Cash widget (v.1.2.1) to refresh it, the value jumps between the actual value and +-$676. Used on a stock Samsung S7 on Android 7. (Original Bitcoin widget works correctly)

**Comment by hwki** [comment]
Unable to replicate. If this is still occurring after the latest release, please open a new issue along with the exchange that is having the problem.
