### ISSUE TITLE
Peercoin support

### ISSUE THREAD

**Issue by jondo** [hwki/SimpleBitcoinWidget#30]
I understand that support for additional currencies will not happen soon, but please keep this issue open for tracking the request for a [Peercoin](https://peercoin.net/) version. Peercoin was forked from Bitcoin, so it might be feasible.

**Comment by hwki** [comment]
PeerCoin currently has a small market cap, so it won't be supported in the widget for now (I have to draw the line somewhere). I will leave this issue open if it grows in popularity.

**Comment by hwki** [comment]
Added Peercoin.

**Comment by jondo** [comment]
The latest F-Droid version 6.6 does not contain this yet :-(

**Comment by hwki** [comment]
Argh, looks like I neglected to push the tags up, sorry. Its done, I don't know how long it will take for a new F-Droid build. Thanks for letting me know.
