### ISSUE TITLE
Decred support

### ISSUE THREAD

**Issue by raedah** [hwki/SimpleBitcoinWidget#35]
We would like support for Decred.
https://coinmarketcap.com/currencies/decred/

We didnt think it was coming so we made this, but are open to collaboration.
https://github.com/C-ollins/Simple-Decred-Widget
https://play.google.com/store/apps/details?id=com.simpledecredwidget

**Comment by hwki** [comment]
App looks good. I don't think I'll be adding support for Decred soon, I plan on only adding coins when either there is a lot of demand for them or they have a large enough market cap.

**Comment by hwki** [comment]
Added Decred.
