### ISSUE TITLE
[Exchange Request] Coinbe.net

### ISSUE THREAD

**Issue by JuniorJPDJ** [hwki/SimpleBitcoinWidget#37]
Hi,
I want to show you exchange, which has all coins implemented in your app, and much much more ;)
It's small polish exchange which just started and is going great.
https://coinbe.net
You can find Public API here: https://github.com/beatcoinpl/Public-API
And Private API here: https://github.com/beatcoinpl/Private-API

**Comment by hwki** [comment]
Added
