### ISSUE TITLE
Widget greyed out after recent update

### ISSUE THREAD

**Issue by steevithak** [hwki/SimpleBitcoinWidget#39]
Since the most recent update, my bitcoin widget has been greyed out and the price no longer updates. If I touch it to force a reload, I get the spinner for a few seconds and then it goes back to being greyed out with no update in price. Also tried restarting Android but that didn't help either. I'm on a Google Pixel 2 w/Android 8.1.0, build OPM2.171019.029, patch level Apr 5, 2018

**Comment by hwki** [comment]
Please tell me the coin, exchange, and currency your widget is configured for.

**Comment by steevithak** [comment]
Bitcoin & US dollars. I think the exchange was the one called "average price" or something like that? Is there a way to see the current config - I don't see a way to access the settings once the widget is active.

**Comment by hwki** [comment]
Unfortunately not. Couple more questions: did you download this from Google Play or F-Droid, and do you have any battery saver/data saver settings on at the moment?

**Comment by steevithak** [comment]
Got it from Google Play. I've been using it for a long time, since my previous Nexus 5X phone I think. Haven't noticed an issue like this before. No special battery saver settings, full bars on cellular data, and have a full power WiFi signal. I wonder if I should try deleting the widget and adding it back? I may give that a shot just to see what happens...

**Comment by steevithak** [comment]
That did it! I removed the widget and added it back. Seems to be working fine again. At least it was an easy fix whatever the cause.

**Comment by hwki** [comment]
Not sure what would have happened here, but glad its working again. Closing this issue for now.

**Comment by hwki** [comment]
Still unable to reliably reproduce, but I've seen this happen after restarts and/or loss of internet. Removing/adding a new widget seems to fix problem.

**Comment by hwki** [comment]
Potentially fixed with 6.9.1
