### ISSUE TITLE
no size to see information

### ISSUE THREAD

**Issue by EBII** [hwki/SimpleBitcoinWidget#49]
Hello i don't know if you can help me but i use private android version name 
/e/ "my data is my data" for personnal and corporate privacy. 
https://e.foundation/
so they develop there own launcher name Bliss  i think 
i use to work with your widget on lineageOs and it's work fine
but with /e/ this is the result in picture. 
![IMG_20190516_182407_598](https://user-images.githubusercontent.com/4985100/57970910-90e54080-7987-11e9-9aa0-97eb95bcf570.jpg)

**Comment by hwki** [comment]
There might not be much I can do about this, the widget uses the height/width given by the launcher, which seems to be incorrect. And without being able to download the launcher myself I can't verify what data the widget is being given. Do they work better after resizing to a smaller width, or is it an issue at any size?

**Comment by hwki** [comment]
Unfortunately it seems to work fine for me:
![Screenshot_1558631690](https://user-images.githubusercontent.com/571913/58272548-6f53d280-7d54-11e9-9fa8-832f15cd742d.png)

I'll keep looking when I can.
