### ISSUE TITLE
Phone restart

### ISSUE THREAD

**Issue by tim222tim** [hwki/SimpleBitcoinWidget#53]
I've been using Simple Bitcoin Widget for years. Recently my phone (Pixel 3) started restarting spontaneously. It seems to be related to when Simple Bitcoin Widget is gray because it can't reach the exchange. Has something changed in a recent version that could be causing this?

Thanks for a cool widget!

**Comment by hwki** [comment]
The widget is almost definitely not causing your phone to restart. What you are seeing is the bug related to issue #39 . I haven't been able to find the exact scenarios to cause it to happen in order to fix it, but it does seem to occur after a loss of connectivity and a restart of the device.

**Comment by tim222tim** [comment]
I agree that it should be unlikely for the the widget to be able to cause the phone restarts, but the circumstantial evidence is growing. I have had three episode now of my phone repeatedly restarting on its own. Each time corresponded with Simple Bitcoin Widget being grayed out, and the restarts stopped happening when I removed the widget and added it back to my home screen. Perhaps there is an OS bug that gets triggered by whatever is causing SBW to gray?

**Comment by hwki** [comment]
Can you post your details on model of phone, android version, launcher, and what exchange/currency you are using for each widget you have?

**Comment by tim222tim** [comment]
Pixel 3
Android 9 Build PQ3A.190705.003
Pixel Launcher
I am using one widget: Coinbase / Bitcoin

**Comment by hwki** [comment]
So that's basically the same setup that I have on my personal device, except mine is a Pixel 2. I'm not seeing any matching crashes in the google play dev console.

When the widget turns gray, that just means that it hasn't been able to get data from the exchange for some time (whether from no internet or exchange being down). It literally just changes the color. It doesn't change any behavior, and I can't think of any way to cause a phone to restart. It does seem like something else would be causing this. I'm still thinking the grayed out widget and the restart are a side effect of the same thing.

**Comment by tim222tim** [comment]
I do see your point. I have been using the widget for years, and am familiar with the widget graying and then returning to color when the site is not available. Perhaps in the case they are symptoms of the same issue. I will let you know if I gather any further data points.

**Comment by hwki** [comment]
I'd appreciate that. I've been trying to figure out issue #39 for a long time now and I can't ever reproduce it enough to debug it. Though I think its more of an android or launcher bug I'd still like to figure out a workaround.

**Comment by hwki** [comment]
Another thing to consider.. what is your refresh time set to? Maybe its having an effect if its too short?

**Comment by tim222tim** [comment]
Ah. Yes, my refresh time is set to five minutes. Why do you think this could lead to trouble?

**Comment by hwki** [comment]
I'm just guessing. Worth trying a longer time to see if it changes anything.

**Comment by tim222tim** [comment]
I will do that.
