### ISSUE TITLE
Support additional coins

### ISSUE THREAD

**Issue by hwki** [hwki/SimpleBitcoinWidget#61]

**Comment by hwki** [comment]
OmiseGO

**Comment by hwki** [comment]
Basic Attention Token

**Comment by hwki** [comment]
Golem

**Comment by hwki** [comment]
Power Ledger

**Comment by hwki** [comment]
Zcoin

**Comment by hwki** [comment]
Gulden

**Comment by hwki** [comment]
Komodo

**Comment by hwki** [comment]
Pirate

**Comment by hwki** [comment]
Grin

**Comment by hwki** [comment]
ChainLink

**Comment by hwki** [comment]
Teloscoin

**Comment by Sami32** [comment]
- LEND (Aave)
- SNX (Synthetix Network Token)
- BAND (Band Protocol)

- CEL (Celsius)
- MLN (Melon)
- GNO (Gnosis)

- PAXG (PAX Gold)
- XAUt (Tether Gold)
- DGX (Digix)

*OmiseGO as officially by renamed OMG Network

**Comment by joergi** [comment]
Near?

**Comment by Sami32** [comment]
- Avalanche (AVAX)
- Travala.com (AVA)
- ZCOIN has been rebranded to Firo (FIRO)

**Comment by hwki** [comment]
thanks @Sami32. Will look at adding the rest next release.
