### ISSUE TITLE
Price change, chart, UI fixies.

### ISSUE THREAD

**Issue by ghost** [hwki/SimpleBitcoinWidget#63]
Hi, I like the app because of simplicity. 

But to be able to use it I need 

1. some background chart over the price to have notion of the price change
2. some difference in price (percentage over last, day, 7days, month,...)

Also the spacing and space efficiency of the widget is not really fitting. 

----

I am willing to pay some bitcoin to have a great open source app like this. 😉

**Comment by petrhejna** [comment]
I used to have https://play.google.com/store/apps/details?id=com.crypter.cryptocyrrency

But it became quite cluttered.

**Comment by petrhejna** [comment]
![Screenshot_20191216-002919_1](https://user-images.githubusercontent.com/383295/70871037-2c30a980-1f9b-11ea-8f36-a3b8867b9e51.jpg)


This is what I mean "not possible to make smaller vertically". 

On the image the with is already 1 block, but height is 2 blocks. And it is **not possible to make smaller**.

**Comment by hwki** [comment]
The widget is completely resizable down to what works out to a height of 1 and width of 2. If you're not able to resize the height smaller than the screenshot, it would seem to be an issue with the launcher. The spacing also looks quite unusual. Can you tell me what launcher you are using? It might not be reporting the available widget size correctly.

As for your other suggestions, although they have been mentioned before I will not be adding them to the widget. It is intended to be simple and this would clutter both the UI and the code considerably, and I don't have the free time to add that much functionality into a free app. There are many other great crypto widgets out there that might work better for you.

**Comment by petrhejna** [comment]
I'm sad to head that about not adding me features. I am struggling to find some OS alternative to ad-cluttered app I mentioned.

The UI like this seem to me pretty simple and not cluttered

![Screenshot_20191216-070506_1](https://user-images.githubusercontent.com/383295/70883273-b811f800-1fd2-11ea-8896-bf9c4a5309d0.jpg)

But I respect your choice.

**Comment by petrhejna** [comment]
> Can you tell me what launcher you are using? It might not be reporting the available widget size correctly.

OnePlus Launcher

**Comment by petrhejna** [comment]
Also I would suggest to dropp the border. Just remove it.
