### ISSUE TITLE
Coin request: Teloscoin

### ISSUE THREAD

**Issue by luxleather** [hwki/SimpleBitcoinWidget#65]
Teloscoin (TELOS) have good user base and I am sure many would use app with this coin on it. To make process easier I made pictures for app which can be used.
[ic_telos.png](https://i.imgur.com/vyX1aOD.png)
[ic_telos_gray.png](https://i.imgur.com/h5XMjkR.png)

Teloscoin is listed on: Biki, Graviex, Soutxchange, WhiteBit
[https://coinmarketcap.com/currencies/teloscoin/](https://coinmarketcap.com/currencies/teloscoin/)

but you can use Coingecko API for app.
[https://www.coingecko.com/en/coins/teloscoin](https://www.coingecko.com/en/coins/teloscoin)

Hope to see it alive after next app update.

**Comment by hwki** [comment]
Added to coin request issue: https://github.com/hwki/SimpleBitcoinWidget/issues/61#issuecomment-594832806
