### ISSUE TITLE
Provide Icon in different sizes

### ISSUE THREAD

**Issue by Yonjuni** [hwki/SimpleBitcoinWidget#7]
Thanks for the widget. In your drawable folder you only provide one app icon size (https://github.com/hwki/SimpleBitcoinWidget/blob/master/mobile/src/main/res/drawable/bitcoinwidgeticon.png) 

This causes problems in other applications which are accessing the the Android package manager, see https://github.com/SecUSo/privacy-friendly-netmonitor/issues/22 

Here is a sizing chart for icons sizes: 
https://developer.android.com/guide/practices/ui_guidelines/icon_design_launcher.html

**Comment by hwki** [comment]
Thanks for letting me know. I've rolled out a fix.
