### ISSUE TITLE
Installed app cannot be opened

### ISSUE THREAD

**Issue by Andertuc** [hwki/SimpleBitcoinWidget#73]
I just installed the app via F-droid. According to the F-droid app it is installed, but neither does F-droid show a button to open it nor can I find it on the device (Samsung Galaxy S7). How can I solve this? Thanks a lot in advance.

**Comment by hwki** [comment]
@Andertuc There is no corresponding app, it is just the widget. You need to add it like any other widget.
Instructions for your device: https://www.samsung.com/uk/support/mobile-devices/what-are-widgets-and-how-do-i-add-them-to-my-android-smartphone-or-tablet/

**Comment by Andertuc** [comment]
I followed the above mentioned instruction and failed in the third step. The widget cannot be found there, neither by scrolling nor by using the search.

**Comment by hwki** [comment]
It installs and appears fine for me from F-Droid. If its not appearing this is most likely an issue with F-Droid, not with the app. I would try uninstalling and reinstalling, or restarting your phone.
