### ISSUE TITLE
Support additional exchanges

### ISSUE THREAD

**Issue by Sami32** [hwki/SimpleBitcoinWidget#74]
~(Huobi Global)~
~Uniswap: Can't add at this time, widget requires a public REST API~
~Deversifi~

Binance DEX: API looks too complicated to integrate into widget at this time.
Yeah, a guy that implemented Binance API for trading told exactly the same thing ;)

~ProBit~

**Comment by Sami32** [comment]
* Bithumb Global
https://github.com/bithumb-pro/bithumb.pro-official-api-docs/blob/master/rest-api.md

- Note about UniSwap (before v3 that could provide a native REST API):
https://bitquery.io/blog/dex-data-apis

**Comment by Sami32** [comment]
- Uphold
https://uphold.com/en/developer/api/documentation/#introduction

**Comment by maestro-brentpanther** [comment]
Uphold has already been added

**Comment by Sami32** [comment]
Oups..my bad i didn't verified it after having done a such report to CoinGecko :~

**Comment by Maingron** [comment]
I would like to see support for Giftocoin :)

**Comment by Kreuger** [comment]
Hey. Would it be possible to add support for NDAX?

**Comment by hwki** [comment]
@Kreuger hmm, I am seeing it. where did you get the update from, and what coin are you trying with?

**Comment by Kreuger** [comment]
I just realized the issue. Had to change my currency to CAD first. Thanks!
