### ISSUE TITLE
Screenshots for F-Droid 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hwki/SimpleBitcoinWidget#75]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by hwki** [comment]
Added, thanks.

**Comment by hwki** [comment]
@mondlicht-und-sterne Any idea why the app isn't updating in F-Droid? I see it pulled in the metadata changes, and its not in the failing builds list.

**Comment by mondlicht-und-sterne** [comment]
do you mean the update is not coming online?
it probably takes longer at the moment. but i can't tell you why. mine is also currently waiting to come online.
