### ISSUE TITLE
[Feature Request] Display calcualted value of holdings instead of price of 1.

### ISSUE THREAD

**Issue by DePingus** [hwki/SimpleBitcoinWidget#78]
This is such a nice widget! Any chance of adding the ability to enter my total whatevercoin holdings and instead of displaying the price of 1 whatevercoin, the widget displays the calculated value of my holdings?

EDIT:
I just saw how another app does it. They have a "Number of Coins" option when creating the widget. It defaults to 1. Changing that makes the widget display the calculated value.

**Comment by hwki** [comment]
My concern with adding this is that it wouldn't be as useful unless you had the ability to edit the number of coins on an existing widget. And editing a widget is a lot more work than it would seem (needing either an edit button somewhere on the widget or a whole new UI for managing existing widgets).

**Comment by DePingus** [comment]
I hear you. The other app I was looking has you set the number of coins when you first create the widget, but it also has an actual app UI that lets you edit your existing widgets (as you mentioned). With your widget only approach the user would have to delete and recreate the widget every time they bought or sold coins. Not a big deal if you buy rarely and hold, but a bit of a pain for frequent traders. I'm going to close this feature request. I appreciate the work you've done. Thanks!
