### ISSUE TITLE
[Feature Request] Add 'mobilecoin' to supported coins

### ISSUE THREAD

**Issue by crassd** [hwki/SimpleBitcoinWidget#79]
Hello,

I was wondering if MobileCoin could be added to the supported coins. I see it's being tracked by Coinbase (at least the value is, even though trades are not supported), please let me know if I can provide any assistance in adding support.

Thank you.

**Comment by hwki** [comment]
Partial support has just been added in the latest release, which is now live on Google Play, and will be rolling out to F-Droid probably in the next few weeks.

**Comment by crassd** [comment]
Thanks for the fast response, looking forward to seeing it on F-Droid soon.
