### ISSUE TITLE
Add option to show amount of coin per currency

### ISSUE THREAD

**Issue by sp-icy** [hwki/SimpleBitcoinWidget#84]
Hi,

first of all: Thank you for this nice piece of software. :-)

Currently (v. 7.4.1) the widget shows the price of a coin (amount of currency per coin).

I suggest to add an option to show the reciprocal value, i.e. the price of a currency (amount of coin per currency).

Example: If a user wanted to see how many Satoshis can be bought for one USD (aka Moscow Time), the widget would have to be created with the following settings:

- Coin: BTC
- Currency: USD
- Symbol: Do not show currency symbol. (The Dollar symbol would be confusing because it's Sats, not Dollars.)
- Denomination: Satoshis
- Check [New Option] "Show reciprocal value" or "Show amount of coin instead of currency" or whatever you like to name it.

I think this enhancement would still keep it simple. ;-)

Thanks in advance for considering.

**Comment by hwki** [comment]
Added with 8.1

**Comment by zatJUM** [comment]
Would be nice to display "Moscow time" as a special feature for BTC, with only sats displayed (no "0.0000" at the begining), and https://satsymbol.com/fontawesome/ as the symbol of the currency.
