### ISSUE TITLE
Disable fetching rss when sync is disabled

### ISSUE THREAD

**Issue by ReleaseStandard** [hwki/SimpleBitcoinWidget#85]
Simple Bitcoin Widget fit perfectly my needs thank you so much !

Is your feature request related to a problem? Please describe.
I'm frustrated when I disable sync (from the tile) and see that handy news reader continue fetching rss feed.

Describe the solution you'd like
It would be great that handy news ready follow user preference isSyncActive ex:
https://stackoverflow.com/questions/11252876/check-if-sync-is-enabled-within-android-app/20098676

Additional context
AccountManager compat API 5
AccountManager.get compat API 5
AccountManager.getAccountsByType API 5
ContentResolver.isSyncActive API 5
Const.ACCOUNT_TYPE API 5
Account API 5
ContentResolver API 1
Need peemissions:
Manifest.permission.GET_ACCOUNTS
Manifest.permission.READ_SYNC_STATS

**Comment by hwki** [comment]
@ReleaseStandard  I think you have the wrong repo.
