### ISSUE TITLE
Font size is too small

### ISSUE THREAD

**Issue by steevithak** [hwki/SimpleBitcoinWidget#87]
After the latest update, the font size used to show the bitcoin price is substantially smaller, making it harder to read (at least on my phone, I'm using a Pixel 4a 5G). Is there an option to increase the font size back to the size it was on previous versions?

**Comment by hwki** [comment]
@steevithak  Please attach a screenshot so I can tell if this is expected or a bug.

**Comment by steevithak** [comment]
Here's what it looks like now. Previously the type size was bigger than this

![Screenshot_20210928-113142](https://user-images.githubusercontent.com/660193/135129329-609b39e2-74ec-4e12-bc23-cf89e4fec4ec.png)

**Comment by hwki** [comment]
Yes, that is how it should look. You can always resize the widget to make it bigger, or turn the icon off to have more room for text. The changes were necessary to handle issues with how various launchers handle padding (or more correctly don't handle well) as well as widget updates for Android 12.
Also other launchers (such as Nova Launcher), will allow you to turn off padding giving you more room.

**Comment by steevithak** [comment]
Ah, ok. I didn't know the widget allowed resizing. I tried that and it seems to have the really small default size and jumps immediately to a really big size if you expand it even slightly. But I can live with the bigger size, at least it's easier to read. Thanks!

**Comment by hwki** [comment]
I have pushed out an update that decreases the padding a bit and should bump up the text size a bit more.
