### ISSUE TITLE
Add other currencies 

### ISSUE THREAD

**Issue by Roxxor91** [hwki/SimpleBitcoinWidget#9]
Hey!
Would you be up to add additional cryptocurrencies? I really like this clean simple widget! It would be perfect if I could create several of them with different currencies, so I can spread them over my homescreen 😃
Thanks already for the widget in its present state!

**Comment by hwki** [comment]
Sorry, I probably won't do that just for the sheer amount of time that would involve. I have considered creating a separate Ethereum and Litecoin widget if I can find the time.

**Comment by hwki** [comment]
@Roxxor91 I've made an Ethereum and a Litecoin widget:
https://play.google.com/store/apps/details?id=com.brentpanther.ethereumwidget
https://play.google.com/store/apps/details?id=com.brentpanther.litecoinwidget
