### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [hwki/SimpleBitcoinWidget#96]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 16  warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on SimpleBitcoinWidget (or its library dependencies). We documented each one of these issues in private gists for the sake of confidentiality (non-disclosure). 

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve SimpleBitcoinWidget's security, and the quality of the reports of static analysis tools.
(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by vehs-brentpanther** [comment]
Yes, you can share them with me at apps@brentpanther.com if you'd like.

**Comment by hwki** [comment]
Yes, you can share them with me at apps@brentpanther.com if you'd like.

**Comment by misterAnderson90** [comment]
Hello Brent,

Thanks for your interest in receiving the gists. I have sent you by e-mail. 

Please let me know if you have any questions.

**Comment by hwki** [comment]
Updated affected third party libraries to latest versions
