### ISSUE TITLE
No currencies/exchanges found for this coin!

### ISSUE THREAD

**Issue by mrplumber** [hwki/SimpleBitcoinWidget#98]
I get this error every time I try to create new widget for DOGE (or any other currency I tried for that matter) in currency selection window:
_No currencies/exchanges found for this coin!_

Simple Bitcoin Widget version: 8.1.9 (F-Droid)
Device: Nexus 5X (bullhead)
Android version: 8.1.0
OS: Lineage 15.1

**Comment by hwki** [comment]
I think this happens when the coin data cache is corrupted on your device. 
Please try clearing your app storage and try again (Settings > Apps > Simple Crypto Widget > Storage > Clear Storage)

**Comment by mrplumber** [comment]
That helped. It works now. Thank you.
