### ISSUE TITLE
Add price denomnination in other coins

### ISSUE THREAD

**Issue by RequestPrivacy** [hwki/SimpleBitcoinWidget#99]
Right now (version 8.1.9) it is possible to denominate the price of a cryptocurrency either in fiat (e.g. $/BTC) or inverse, in the cryptocurrency (e.g. BTC/$).

For people with a favorite coin and the ones who already switched their unit of account to their favorite coin, it would be beneficial to express price of other coins denominated in the unit of account (e.g. XMR/BTC).

Note: as the numbers can become really small (the above example is right now around XMR/BTC = 0.00532451) the display in the widget could become somewhat ugly. Nevertheless I think it would be a valuable option to have.

**Comment by hwki** [comment]
This is already possible. Coins also appear in the currency list if supported by an exchange. You can for example select XMR then select BTC as the currency.

**Comment by RequestPrivacy** [comment]
Excuse my ignorance, I missed it as I thought the menu is just for selecting different fiats. 

Now, as I denote everything in BTC the price of other coins is rather small. It seems as if there are only 5 decimal places, regardless of the width of the widget. Would it be possible to add more places to get a more precise number? 

At least with a full width widget the font could be decreased to gain the space imho. If that isn't an option feel free to close the issue!

Love the widget, thanks for your work!

**Comment by hwki** [comment]
Yes, I think that will be handled by fixing https://github.com/hwki/SimpleBitcoinWidget/issues/62. I don't have an estimate when that will be though.
